### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by flpfar** [Zubenna/newsweek-clone#2]
Great job so far, Nnamdi!!

Some improvements you could implement:
-In header and main, use different div for row and container-fluid.
-Remove 'active' from you nav-bar. They are used only for the current page.
-Check your indentation to make your code easier to read. 
-In debate, you can use cols inside the row to prevent the text from going to the bottom of the image.
-Use justify content so your header shouldn't break
-In 'tabs', try not to use a fixed with. You can add padding to text to create its size.
-Try to use more bootstrap for padding and margin, it can make it easier for responsiveness.
-To create the triangle, use borders top and left, border-size and height 0;

Keep the great work, man!!

**Comment by rootDEV2990** [comment]
hey bro heres the triangle try it  out in a editor and you can change the values as you need. try to increase the height and width to get a feel for how its rendered. 

```
.triangle {
 width: 0;
 height: 0;
 border-top: 50px solid red;
 border-right: 50px solid blue;
 border-bottom: 50px solid green;
 border-left: 50px solid yellow;
}

<div class"triangle"></div>
```

[test.html.zip](https://github.com/Zubenna/newsweek-clone/files/4487985/test.html.zip)

**Comment by Zubenna** [comment]
Recommendations has been implemented.
